### ISSUE TITLE
Digraph completion with ignorecase

### ISSUE THREAD

**Issue by jnd-au** [chrisbra/unicode.vim#10]
Hi, when ignorecase is set in a buffer, completing simple digraphs like a' is difficult because `unicode#CompleteDigraph()` brings up a menu with the capital Á first and the lowercase á second. For me, case sensitive matching is desirable, by patching the patterns in autoload/unicode.vim to include \\\\C in lines 390-391:

```vim
let filter1 = printf("match(v:val, '\\C%s%s')>-1",  prevchar1, prevchar)
let filter2 = printf('match(v:val, ''\\C%s\|%s'')>-1', prevchar1, prevchar)
```

 However, perhaps it should be configurable? There are three options: always case sensitive (\\\\C), always case insensitive (\\\\c), or the current default: according to buffer’s ignorecase setting.

**Comment by chrisbra** [comment]
I think, it should match and not ignore case. For now I'll just add the `\\C` as suggested. Thanks for the feedback!
