### ISSUE TITLE
Commands to define digraphs by hex number or character name

### ISSUE THREAD

**Issue by bpj** [chrisbra/unicode.vim#14]
Hi Christian,

this is in followup to your list post the other day. I mostly use keymaps for serious multilingual work, which I do a lot of, but also use the plugin heavily to write keymaps, and to identify characters, and to look up more seldom used symbols and the like.

This is about a suggested addition to the plugin. I often define temporary digraphs for more seldom used characters and when you recently posted a trick for defining digraphs by hex number I immediately rolled that into a command. Now I got thinking that such a command might be a good addition to the unicode plugin. Thinking further about that I thought it may be possible to combine digraph definition with name completion. Another and perhaps better idea is a command to define a digraph for the character under the cursor.

That's four ideas for commands which would make it easier to define digraphs:
-   Define digraphs by hex number.
  
  ``` vim
  fun! s:mk_hex_digraph(digraph, hexnum)
      if a:hexnum !~ '^[[:xdigit:]]\+$'
          echoerr "HexDigraph expected hexadecimal number as second argument!"
          return
      endif
      exe printf(":dig %s %d", a:digraph, eval('0x' . a:hexnum))
  endfun
  
  com! -nargs=+ HexDigraph call s:mk_hex_digraph(<f-args>)
  
  HexDigraph DH d0
  ```
-   Define digraphs by Unicode name.
  
  ``` vim
  fun! s:mk_digraph_by_name(arg)
      let matchlist = matchlist(a:arg, '^\(\S\S\)\s\+\(.\+\S\)\s*$')
      if empty(matchlist)
          echoerr "Usage: DigraphByName {char1}{char2} {Unicode name}"
      else
          let [ chars, name ] = matchlist[1:2]
          let regex = '^' . name . '$'
          let unichars = unicode#FindUnicodeBy(regex)
          if len(unichars) == 1
              exe printf(":dig %s %d", chars, unichars[0]['dec'])
          elseif len(unichars) > 1
              echoerr "Unicode name ambiguous: " . name
          else
              echoerr "Unicode name not found: " . name
          endif
      endif
  endfun
  
  com! -nargs=1 DigraphByName call s:mk_digraph_by_name(<f-args>)
  
  " The 'second argument' can be many words and/or a pattern
  DigraphByName bh latin small.*b with stroke
  ```
-   Command combining definition of temporary digraphs with Unicode name completion.
  
  I have only the foggiest how this should be implemented...
-   Command defining temporary digraph for the character under the cursor
  
  I have some idea how to implement this but haven't done so yet.

(Note: I began writing this issue on my phone, and submitted by accident before it was complete,
so I had to rush to a real computer to complete it. On the flip side I could include the actual functions I wrote!)

**Comment by bpj** [comment]
Inevitably I started to play around a bit with the mk\_digraph\_by\_name() function and updated it with some features I have been missing:

-   Normalization of whitespace in the Unicode name.
-   A confirmatory message when the digraph has been defined.
-   Support for [Perl-style abbreviated letter names]: if there is a colon in the argument like `Greek: gamma` the function looks up `greek <case> letter gamma` and `greek letter gamma` in that order and uses the first which matches, where `<case>` is either `small` or `capital` depending on whether the part after the colon contains *any* capital letter, so that `Greek: Gamma` or `Greek: gaMma` are `greek capital letter gamma` while `Greek: gamma` is `greek small letter gamma`.

````vim
fun! s:mk_digraph_by_name(arg)
    let args = matchlist(a:arg, '^\(\S\S\)\s\+\(.\+\S\)\s*$')
    if empty(args)
        echoerr "Usage: DigraphByName {char1}{char2} {Unicode name}"
        return
    endif
    let [ chars, charname ] = args[1:2]
    let names = []
    " test for a perl-style short charname
    let short = matchlist(charname, '^\(\S.\{-}\S\)\s*:\s*\(\S.*\S\@<=\)\s*$')
    if empty(short)
        let names = [charname]
    else
        let [thescript, thename] = short[1:2]
        let thecase = thename =~ '\u' ? 'capital' : 'small'
        call add(names, printf('%s %s letter %s', thescript, thecase, thename))
        call add(names, printf('%s letter %s', thescript, thename))
    endif
    call map(names, "substitute(v:val, '\\s\\+', ' ', 'g')")
    for name in names
        let regex = '^' . name . '$'
        let unichars = unicode#FindUnicodeBy(regex)
        if len(unichars) == 1
            let u = unichars[0]
            exe printf(":dig %s %d", chars, u['dec'])
            echo printf('Digraph %s == %s U+%04X %s', chars, u['glyph'], u['dec'], u['name'])
            return
        elseif len(unichars) > 1
            echoerr "Unicode name ambiguous: " . charname
            return
        endif
    endfor
    echoerr "Unicode name not found: " . charname
endfun
````

  [Perl-style abbreviated letter names]: http://perldoc.perl.org/charnames.html#DESCRIPTION

**Comment by chrisbra** [comment]
I have basically taken your example and made a new command `:DigraphNew` which can either use a hex value or a pattern as shown. Please test current HEAD. Also, if you could perhaps update the documentation for the perl style pattern that would be appreciated.

Also your other suggestions look interesting, althought I am not sure what you mean with temporary digraphs.

**Comment by bpj** [comment]
With temporary digraph I mean digraph which will be used only during the current session. The Idea is that you look up a character using Unicode completion, then with the cursor on that character you define a digraph for it by executing the command with the digraph characters as argument.

**Comment by bpj** [comment]
The best description of the perl style patterns is in the documentation for charnames.pm itself:

> [If] CHARNAME has the form SCRIPT:CNAME, then CNAME is looked up as a letter in script SCRIPT, as described in the next paragraph. 
> [snip]
> For lookup of CHARNAME inside a given script SCRIPTNAME, this pragma looks in the table of standard Unicode names for the names

>       SCRIPTNAME CAPITAL LETTER CHARNAME
>       SCRIPTNAME SMALL LETTER CHARNAME
>       SCRIPTNAME LETTER CHARNAME

> If CHARNAME is all lowercase, then the CAPITAL variant is ignored, otherwise the SMALL variant is ignored

I would paraphrase it as follows and add some examples:

````
This command supports shortcut letter names in the style of Perl's
"charnames" pragma: if {pattern} has the form {scriptname}:{charname},
then it is looked up as a letter {charname} inside a script
{scriptname}: the standard Unicode names are searched for the names

>
      {scriptname} CAPITAL LETTER {charname}
      {scriptname} SMALL LETTER {charname}
      {scriptname} LETTER {charname}

in that order. If {charname} does not contain any uppercase letters,
then the CAPITAL variant is ignored, otherwise the SMALL variant is
ignored. The first character found which corresponds to one of these
names is assigned to the digraph. For example

>
    Short                   Full
    -----------------------------------------------------------------
    Greek: Sigma            GREEK CAPITAL LETTER SIGMA
    greek: siGma            GREEK CAPITAL LETTER SIGMA
    Greek: sigma            GREEK SMALL LETTER SIGMA
    Greek: final sigma      GREEK SMALL LETTER FINAL SIGMA
    Greek: final Sigma      {Error, there is no capital final sigma!}
    ֑Hebrew: shin            HEBREW LETTER SHIN
    ֑Hebrew: sheva           {Error, not a letter but a mark!}
                            ("hebr.*sheva" will work, however!)

Unlike in Perl both {scriptname} and {charname} can be patterns:
"imp.*ar.*:al.*" will match IMPERIAL ARAMAIC LETTER ALEPH!

Note that while this feature can save tedious repetetive typing
it uses ordinary pattern matching and can NOT resolve nonexistent
letters like capital final sigma above or funny lowercase/uppercase
name pairs like U+0195 LATIN SMALL LETTER HV and 
U+01F6 LATIN CAPITAL LETTER HWAIR!
````

**Comment by chrisbra** [comment]
thanks. Included the description.

**Comment by bpj** [comment]
BTW any reason this is still open?

**Comment by chrisbra** [comment]
I think the " temporary digraphs" feature is missing (although by default they are temporary until you add them to your .vimrc). So let's close it.
