### ISSUE TITLE
FindUnicodeByInternal nonintuitively requires its search string to be >1 char long

### ISSUE THREAD

**Issue by hseg** [chrisbra/unicode.vim#15]
When I execute :UnicodeSearch x or :UnicodeSearch 0, vim gives me the following error:
> Error detected while processing function unicode#PrintUnicode..<SNR>62_FindUnicodeByInternal:
> line   16:
> No argument was specified!

If I understand the code correctly, the problem is that FindUnicodeByInternal isn't considering the edge
cases where `match` is a string of length 1, consisting of a nondigit or 0.
In those cases, the guard `len(a:match) > 1 && digit == 0` fails, so `name` isn't set and is therefore
empty, while `digit` will be `0`, by Vim's string-to-number conversion rules.
Hence, the guard `digit == 0 && empty(name)` falls through, giving the non-intuitive error message that
`"No argument was specified!"` when clearly a nonempty argument was passed.

Fix: Replace `len(a:match) > 1` by `len(a:match) >= 1`.
Question: Why are we forbidding the call `FindUnicodeByInternal(0)`? `U+0000` is a perfectly valid
codepoint.

**Comment by chrisbra** [comment]
thanks. I think I have fixed this. Please check.
