### ISSUE TITLE
F4 is used by too many plugins by default

### ISSUE THREAD

**Issue by ryanmorillo** [chrisbra/unicode.vim#17]
I'm sure that you can put in a different default binding ( Ctrl-Shift-U comes to mind) for the combining digraph.  I already have several other plugins that I have to change/comment out every time they update because of F4.  This plugin is so useful without that minor function, and it's so easy to do yourself that it should be left commented out like the ga for unicode ga is.

**Comment by chrisbra** [comment]
Hi Ryan!

On Fr, 23 Sep 2016, Ryan Morillo wrote:

> I'm sure that you can put in a different default binding (
> Ctrl-Shift-U comes to mind) for the combining digraph.  I already have
> several other plugins that I have to change/comment out every time
> they update because of F4.  This plugin is so useful without that
> minor function, and it's so easy to do yourself that it should be left
> commented out like the ga for unicode ga is.

Actually ctrl-shift keybindings are no really good choice. However I 
just made a change. Please check.

Liebe Grüße
Christian
-- 
Lieber spät und richtig, als nie und falsch.
