### ISSUE TITLE
unicode.vim overrides my mapping

### ISSUE THREAD

**Issue by teto** [chrisbra/unicode.vim#19]
I have in my "init.vim" (neovim) the following mapping `nmap <f4> <Plug>(QuickFixCurrentNumberLNext)` which got overriden by unicode.vim with:
```
if !hasmapto('<Plug>(MakeDigraph)', 'n') || maparg('<f4>', 'n') ==# ''
    nmap <F4> <Plug>(MakeDigraph)
endif
```
This made me lose some data once as I did not understood that I was using digraphs (thought it was a neovim bug) instead of my :lnext mapping and messed up (my fault as well) with the undo tree. 
I wish unicode.vim would not override my mappings either with an option or by replacing '||' with '&&'

Thanks for the great plugin.

**Comment by chrisbra** [comment]
thanks. Fixed it

**Comment by teto** [comment]
great thanks !

2016-12-02 14:24 GMT+01:00 Christian Brabandt <notifications@github.com>:
