### ISSUE TITLE
Insert unicode characters when found

### ISSUE THREAD

**Issue by Erotemic** [chrisbra/unicode.vim#20]
It would be nice to have a feature where it allowed you to insert one of the characters in a :UnicodeSearch result using a 0-9 number.

**Comment by bpj** [comment]
@chrisbra This looks like a great feature (something I've been missing in fact) but it seems you have forgotten to add `-bang` to the [definition of :UnicodeSearch](https://github.com/chrisbra/unicode.vim/blob/master/plugin/unicode.vim#L40)!

**Comment by chrisbra** [comment]
oh you are right. Forgot to add those changes there as well. fixed it.

**Comment by Erotemic** [comment]
Wow, thanks for the quick patch! This really helps my workflow. 

It might also be useful to add something like this to the README: 
```
:SearchUnicode!   - Search for and insert specific unicode char (need to move to end of the page before insert dialog appears)
```
This way its clear that this functionality is now available.

**Comment by chrisbra** [comment]
okay, updated README.md as well
