### ISSUE TITLE
"See CHANGELOG.md" at the bottom of the helpfile is not very useful.

### ISSUE THREAD

**Issue by tonymec** [chrisbra/unicode.vim#26]
For someone who downloaded this plugin from the vim.org Scripts site, "See CHANGELOG.md" as the only contents of ":help unicode-plugin-history" is not very useful. I suggest putting a full path there instead, i.e. "See https://github.com/chrisbra/unicode.vim/blob/master/CHANGELOG.md".

**Comment by chrisbra** [comment]
thanks tony
