### ISSUE TITLE
Make :DigraphNew not verbose

### ISSUE THREAD

**Issue by hgiesel** [chrisbra/unicode.vim#30]
At the moment, it spouts a confirmatory message, e.g. 

    Digraph h* == η U+03B7 GREEK SMALL LETTER ETA

upon execution. If you want to use this in your vimrc setup, this is completely impractical.

Making it quiet, would allow it to use in vimrc, instead of just interactively...

**Comment by chrisbra** [comment]
what do you mean? Please give exact steps that reproduce the problem.

**Comment by bpj** [comment]
What about an optional bang to make it silent?

fre 14 dec. 2018 kl. 17:14 skrev Christian Brabandt <
notifications@github.com>:

**Comment by chrisbra** [comment]
Have you tried :silent?

**Comment by chrisbra** [comment]
`:silent` seems to work. So use that.
