### ISSUE TITLE
Enter Unicode character in search mode

### ISSUE THREAD

**Issue by mb720** [chrisbra/unicode.vim#34]
Hi and thanks a lot for unicode.vim!

Assuming I have entered search mode with `/`, can I use this plugin to enter a Unicode character in order to search for it in the current file?

Let's say I wanted to search for the owl emoji 🦉 in the current file. Is there a way similar to entering "owl" in Vim's search bar at the bottom, then pressing `c-x c-z`, picking the emoji from the list and then searching for that emoji in the current file by hitting enter?

**Comment by chrisbra** [comment]
You can use `:UnicodeName! /` to store the regex atom for the character under the cursor in the search register.

Alternatively, I just added a commit so you can search from the `/` prompt:

in the search prompt, type `<Ctrl-R>=unicode#Regex(unicode#Search('owl'))<cr>`

**Comment by mb720** [comment]
Thanks for the quick response!

`:UnicodeName! /` gives
> E477: No ! allowed


Am I using this right?

**Comment by chrisbra** [comment]
Sorry, remove the `!`

**Comment by mb720** [comment]
Thanks, I got it now.


This works great:

    <Ctrl-R>=unicode#Regex(unicode#Search('owl'))

I'll put that in a mapping to make it more convenient.
