### ISSUE TITLE
Lookup by html code

### ISSUE THREAD

**Issue by masaeedu** [chrisbra/unicode.vim#35]
Hello. Would it be possible to index the Unicode data by the associated HTML entity (where defined) and allow the user to autocomplete symbols like `&iff;` or `&vee;` within the editor?

**Comment by chrisbra** [comment]
If I understand you correctly, this should be possible. You want an extra completion function for html like entities, right?

**Comment by masaeedu** [comment]
That's right. Basically I want the to be able to type `&if`, then hit `C-X C-<something>` and get a completion list that suggests `⇔` at the top.

**Comment by masaeedu** [comment]
@chrisbra Thank you! I'm trying this behavior out and am seeing something a little bit unexpected https://asciinema.org/a/zrTZ31aBYKcC5tBWe0rh7n53P. Do you think this just comes down to the tab completion in my neovim being misconfigured?

**Comment by masaeedu** [comment]
It seems like it actually inserts the name of the HTML entity instead of the actual character it corresponds to.

**Comment by chrisbra** [comment]
Yes it inserts the entity name. I thought that was what you wanted?

**Comment by masaeedu** [comment]
@chrisbra I was actually looking for a way to insert the actual character, but to refer to it by the HTML entity name (which I'm familiar with) instead of the Unicode identifier (which I'm not familiar with).

E.g. the Unicode name of the corresponding to `&Implies;` is `RIGHTWARDS DOUBLE ARROW`. This isn't something I would remember off the top of my head, and it doesn't seem like there the `<C-X><C-Z>` completion

**Comment by chrisbra** [comment]
I have further redefined the default completion function. You can now also search by html entity name.

**Comment by masaeedu** [comment]
Awesome. Thanks again for all your work on these Vim plugins!
