### ISSUE TITLE
Support nerd font characters

### ISSUE THREAD

**Issue by ranebrown** [chrisbra/unicode.vim#39]
Is there a way to add the [nerdfont](https://www.nerdfonts.com/) characters to the Unicode search list? It looks like the characters are defined in some [shell scripts](https://github.com/ryanoasis/nerd-fonts/tree/master/bin/scripts/lib).

**Comment by chrisbra** [comment]
is there somewhere a list of characters defined, that nerdfont uses?

**Comment by ranebrown** [comment]
I didn't find anything other than the linked shell scripts.

**Comment by chrisbra** [comment]
ping @ryanoasis perhaps he knows better. There are a couple of shell scripts, so which one should I have a look at?

**Comment by ryanoasis** [comment]
Answered in https://github.com/ryanoasis/nerd-fonts/issues/448#issuecomment-593779221

I don't know if there currently are any of the scripts that would work for the purpose but maybe?

**Comment by Finii** [comment]
There now is a list, see

* https://github.com/ryanoasis/nerd-fonts/pull/1137

There is also this (for nvim, I have no clue how good it is)

* https://github.com/ryanoasis/nerd-fonts/issues/1140

![gif](https://user-images.githubusercontent.com/41671631/223701949-88c95719-8371-4572-8573-987e6c17c373.gif)

**Comment by chrisbra** [comment]
thanks, I'll have a look
