### ISSUE TITLE
a' <c-x><c-g> gives " Missing quote" error

### ISSUE THREAD

**Issue by Konfekt** [chrisbra/unicode.vim#4]
`a' <c-x><c-g>` in insert mode gives
```
Error detected while processing function unicode#CompleteDigraph:
line   11:
E115: Missing quote: 'a'')>-1
Error detected while processing function unicode#CompleteDigraph:
line   11:
E116: Invalid arguments for function match(v:val, 'a'')>-1
```

Expected: something akin to `á`

**Comment by chrisbra** [comment]
Thanks for the feedback. I have fixed that now.

**Comment by Konfekt** [comment]
Thanks for the plugin and the prompt fix!

**Comment by chrisbra** [comment]
Hi Konfekt!

On So, 01 Feb 2015, Konfekt wrote:

> Thanks for the plugin and the prompt fix! 

You are welcome.

Best,
Christian
-- 
Niemand würde viel in Gesellschaften sprechen, wenn er sich bewußt
wäre, wie oft er die andern mißversteht.
		-- Johann Wolfgang von Goethe
