### ISSUE TITLE
E325 when running ":UnicodeTable" in 2 Vim instances simultaneously

### ISSUE THREAD

**Issue by lacygoill** [chrisbra/unicode.vim#41]
**Describe the bug**

When executing `:UnicodeTable` in multiple Vim instances, `E325` is raised.

**To Reproduce**

Start Vim like this:

    vim -Nu NORC --cmd 'set rtp^=~/.vim/plugged/unicode.vim' +'UnicodeTable'
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 the path may need to be adapted to point to the local installation of the plugin

Without closing the first Vim instance, start a second one by running the same shell command in a second terminal.

`E325` is raised.

**Expected behavior**

`E325` is not raised.

**Environment**

 - plugin version: 582b715562c953ea9a1f043443f98793cfbc0d47
 - Vim version: 8.2 Included patches: 1-397
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Comment by chrisbra** [comment]
fixed by #42 thanks!
