### ISSUE TITLE
Say thanks link is broken

### ISSUE THREAD

**Issue by jrwrigh** [chrisbra/unicode.vim#43]
saythanks.io was offline for a decent while and was recently brought back up. You'll have to redo the setup again to make it work. There should be more information on the say thanks repo. BlitzKraft/saythanks.io

**Comment by chrisbra** [comment]
urgs, thanks for letting me know.

**Comment by chrisbra** [comment]
So apparently, saythanks now uses the email address instead of the github username, it's not so nice because it leaks the email address and I have to change the link on a bunch of my projects. Oh well...

**Comment by chrisbra** [comment]
I fixed it. Thanks for noticing me.
