### ISSUE TITLE
Command to download 

### ISSUE THREAD

**Issue by voidzero** [chrisbra/unicode.vim#48]
Hi,

In README.md the command to download or update Unicode data is `:DownloadUnicode`, but looking at the following, the command is `:UnicodeDownload`: 
https://github.com/chrisbra/unicode.vim/blob/76e95c6f8c863f5079cd103b18990684bb02d525/autoload/unicode.vim#L126 

Anyway, using either command, the file is downloaded and placed into the proper dir correctly. But I'm wondering if it's possible to 1. download the file over https, and 2. to retain the original timestamp of the file. Using `wget -N` would work and this prevents unnecessary re-downloading of the same file.

**Comment by TredwellGit** [comment]
>I'm wondering if it's possible to 1. download the file over https

See https://github.com/chrisbra/unicode.vim/pull/49.

**Comment by chrisbra** [comment]
I am not sure how to retain the timestamp. https has been included as of #49 (thanks @TredwellGit !)
