### ISSUE TITLE
issue with candidate sorting in completion menu?

### ISSUE THREAD

**Issue by jdhao** [chrisbra/unicode.vim#50]
In insert mode, type `cat` and press `<c-x><c-z>`, the order of listed candidate may need to be tuned. This is the output

![image](https://user-images.githubusercontent.com/16662357/95346065-0095fb80-08ee-11eb-85ad-74fb9218ef69.png)

The actual Unicode characters whose names contain `CAT` are given very low rank. Maybe Unicode characters whose names contain strings starting with `cat` should be ranked first in the completion menu.

**Comment by chrisbra** [comment]
On Mi, 07 Okt 2020, jdhao wrote:

> In insert mode, type `cat` and press `<c-x><c-z>`, the order of listed candidate may need to be tuned. This is the output
> 
> ![image](https://user-images.githubusercontent.com/16662357/95346065-0095fb80-08ee-11eb-85ad-74fb9218ef69.png)
> 
> The actual Unicode characters whose names contain `CAT` are given very low rank. Maybe Unicode characters whose names contain strings starting with `cat` should be ranked first in the completion menu.

Yeah, maybe using the matchfuzzy() function will improve things.
