### ISSUE TITLE
windows UnicodeData.txt download error

### ISSUE THREAD

**Issue by jdhao** [chrisbra/unicode.vim#51]
When using `:UnicodeDownload` command to download the Unicode data on Windows, I see the following error:

> curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

According to post [here](https://stackoverflow.com/q/54938026/6064933), we need to add the `--ssl-no-revoke` option for `curl`.  I have verified that it works.

Based on [your comment in the code](https://github.com/chrisbra/unicode.vim/blob/master/autoload/unicode.vim#L140),  I have changed the value of variable `g:netrw_http_cmd`:

```
let g:netrw_http_cmd="curl --ssl-no-revoke -Lo"
```

**Comment by chrisbra** [comment]
> let g:netrw_http_cmd="curl --ssl-no-revoke -Lo"

I'd rather not change the default netrw http parameters for curl. I believe by default, we should use default parameters and use safe connections if possible and only in case of error try to use parameters that my change security settings.
