### ISSUE TITLE
Add docs/tags to .gitignore

### ISSUE THREAD

**Issue by Grk0** [chrisbra/unicode.vim#6]
Hi!
When installed via Pathogen, `doc/tags` is created when running `:Helptags`, where vim adds documentation tags. Please add that file to `.gitignore` so it doesn't show up as spurious change in git.

Thanks for the excellent vim plugin, btw :-)

**Comment by chrisbra** [comment]
Okay, I have done so.

**Comment by Grk0** [comment]
Thanks a lot for the quick fix!
