### ISSUE TITLE
Providing way to do :DownloadUnicode! to download latest unicode data without prompt

### ISSUE THREAD

**Issue by edi9999** [chrisbra/unicode.vim#64]
When you do :DownloadUnicode, it will prompt you and you have to answer yes.

I think it would make sense to provide :DownloadUnicode! to download the unicode data without any prompt.

**Comment by chrisbra** [comment]
okay, I have enabled this, but only for the `:UnicodeDownload` command. Please use that, as this is the documented command.

**Comment by edi9999** [comment]
Oh, thanks that was quick !

Have a nice day.
