### ISSUE TITLE
Readme <C-x><C-g> looks like Insert mode command

### ISSUE THREAD

**Issue by vds2212** [chrisbra/unicode.vim#66]
I could be wrong but I have the impression that `<C-x><C-g>` are insert mode command and not normal mode command as stated in the readme.

The documentation state so and it seems to work like but the `readme.md` seems misleading.

**Comment by vds2212** [comment]
I have created a Pull request #67 to precise my proposition of improvement.

**Comment by chrisbra** [comment]
thanks, I have included your change, so we can close this :)
