### ISSUE TITLE
Error 734 from line 75 of unicode#GetUniChar

### ISSUE THREAD

**Issue by Hans-Guenter** [chrisbra/unicode.vim#68]
With the latest version I get the message
```
Error detected while processing function unicode#GetUniChar:
line   75:
E734: Wrong variable type for .=
```
I think this can be rectified by applying string() in line 390 of file autoload/unicode.vim:
`let nerd  = string(get(s:nerds, dec, []))`

**Comment by gbarta** [comment]
I had this problem also.  It seems like it would happen for any codepoint not in the nerd font.  I think the default value should be an empty string instead of an empty list:

` let nerd  = get(s:nerds, dec, '')
`

**Comment by chrisbra** [comment]
sorry for that, I just fixed it
