### ISSUE TITLE
Plugin completely broken

### ISSUE THREAD

**Issue by jlconlin** [chrisbra/unicode.vim#69]
This plugin used to work well for me. It seems that perhaps in the last update, something broke and now I can't use it at all. 

For example, when I enter the command `:Digraphs` I get the following error
```
Error detected while processing function unicode#PrintDigraphs[3]..<SNR>166_DigraphsInternal[60]..<SNR>166_GetUnicodeName:
line    5:
E896: Argument of get() must be a List, Dictionary or Blob
Press ENTER or type command to continue
```

When I have `chi` and follow that with `Ctrl-xCtrlg` I get the following error
```
Error detected while processing function unicode#CompleteDigraph[29]..<SNR>166_AddDigraphCompleteEntries[8]..<SNR>166_GetUnicodeName:
line    5:
E896: Argument of get() must be a List, Dictionary or Blob
Press ENTER or type command to continue
```

Either my setup is broken, or the underlying code is broken. Unfortunately, I don't know enough about it to make a change.

**Comment by jlconlin** [comment]
Thanks! That worked well. 

I imagine the first time the plugin tried to download the file, it didn't work because I was behind a firewall.

**Comment by chrisbra** [comment]
thanks. Good to know.
