### ISSUE TITLE
Git repository is large (31MB)

### ISSUE THREAD

**Issue by agonhajdari** [chrisbra/unicode.vim#7]
Hi Christian,

I was able to reduce the size of the repo to 956 KB (The reason for that size is screencast.gif). If you like you can merge it from [here](https://github.com/agonhajdari/unicode.vim.git)

**Comment by chrisbra** [comment]
It won't make the repository smaller if I merge from your fork, right? So what did you do to reduce the size?

**Comment by agonhajdari** [comment]
It is possible through [git subtrees] (https://help.github.com/articles/about-git-subtree-merges) but I wrote a small bash [script]( https://gist.github.com/agonhajdari/8d2ec9a6f363d7908d06) that replicates the steps I did to reduce the size (run it in your local git folder)

**Comment by chrisbra** [comment]
Thanks, I just run your script. It should be okay now.

**Comment by chrisbra** [comment]
Hm, this removed the screencast.gif
That was not so nice

**Comment by agonhajdari** [comment]
I am sorry, I assumed that the screencast was linked from somewere else, because the gif was not in the repo, when I cloned it.

**Comment by chrisbra** [comment]
Yeah, it was put into the gh_pages branch. Fortunately, I found it lying around here locally, so I made a [new repository](https://chrisbra.github.io/vim-screencasts/) and just use this for the screencasts. Will probably also move the other screencasts there.
Thanks anyhow for the helpful script.

**Comment by chrisbra** [comment]
the screencast should be displayed now again. Thanks
