### ISSUE TITLE
Undefined variable: s:nerds

### ISSUE THREAD

**Issue by basicbonobo** [chrisbra/unicode.vim#70]
Getting this when attempting to install the latest version (bc20d0f) in vim 8.2.2121

Error detected while processing function unicode#GetUniChar[118]..function unicode#GetUniChar:                                                                               
line   62:
E121: Undefined variable: s:nerds
E116: Invalid arguments for function get(s:nerds, dec, '')

Tried v21 instead, it seems to work fine.

**Comment by chrisbra** [comment]
Please update your vim.

**Comment by chrisbra** [comment]
> E116: Invalid arguments for function get(s:nerds, dec, '')

I cannot reproduce this error with Vim 8.2.2121. There must be something wrong in your installation. Can you please check, that oyu have this file  `https://github.com/chrisbra/unicode.vim/blob/master/autoload/unicode/nerdchars.vim` in the installation direcotry?

**Comment by basicbonobo** [comment]
Something is odd, for sure. There's only one earlier reference in unicode.vim

let s:nerds= unicode#nerdchars#get_nerd_chars()

And autoload/unicode/nerdchars.vim looks as you would expect:

fu! unicode#nerdchars#get_nerd_chars()
  call s:init_nerd_entities()
  return s:nerds
endfu

fu! s:init_nerd_entities()
  if !exists("s:nerds")
    let s:nerds = {}
    let s:nerds[0X23FB]="Nerdchar: '⏻' iec-power"
    ...


The installation is the latest one of vim-gtk3 from jammy on ubuntu:

$ apt-cache policy vim-gtk3
vim-gtk3:
  Installed: 2:8.2.3995-1ubuntu2.17

$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 03 2024 02:37:51)
Included patches: 1-579, 1969, 580-1848, 4975, 5016, 5023, 5072, 2068, 1849-1854, 1857, 1855-1857, 1331, 1858, 1858-1859, 1873, 1860-1969, 1992, 1970-1992, 2010, 1993-2068, 2106, 2069-2106, 2108, 2107-2109, 2109-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919, 213, 1840, 1846-1847, 2110-2112, 2121

8.2.2121 is what vim reports on startup.

Regardless, I'm good with v21, so I wouldn't spend any time on this unless this turns out to be a common issue.

**Comment by basicbonobo** [comment]
This seems to fix it for me:

---
 Makefile | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/Makefile b/Makefile
index 0ecd631..c943981 100644
--- a/Makefile
+++ b/Makefile
@@ -5,6 +5,7 @@ FTDETECT = $(wildcard ftdetect/*.vim)
 DOC      = $(wildcard doc/*.txt)
 UNIDATA  = $(wildcard autoload/unicode/Uni*.vim)
 HTML     = $(wildcard autoload/unicode/html*.vim)
+NERD     = $(wildcard autoload/unicode/nerdchars.vim)
 PLUGIN   = $(shell basename "$$PWD")
 VERSION  = $(shell sed -n '/Version:/{s/^.*\(\S\.\S\+\)$$/\1/;p}' $(SCRIPT))
 
@@ -37,7 +38,7 @@ undo:
 
 $(PLUGIN).vmb: dummy
 	rm -f $(PLUGIN)-$(VERSION).vmb
-	vim -N -c 'ru! vimballPlugin.vim' -c ':call append("0", [ "$(SCRIPT)", "$(AUTOL)", "$(DOC)", "$(HTML)", "$(UNIDATA)", "$(SYNTAX)", "$(FTDETECT)"])' -c '$$d' -c ":%MkVimball $(PLUGIN)-$(VERSION)  ." -c':q!'
+	vim -N -c 'ru! vimballPlugin.vim' -c ':call append("0", [ "$(SCRIPT)", "$(AUTOL)", "$(DOC)", "$(NERD)", "$(HTML)", "$(UNIDATA)", "$(SYNTAX)", "$(FTDETECT)"])' -c '$$d' -c ":%MkVimball $(PLUGIN)-$(VERSION)  ." -c':q!'
 	ln -f $(PLUGIN)-$(VERSION).vmb $(PLUGIN).vmb
      
 release: version all
--

**Comment by chrisbra** [comment]
good finding. So you used the vimball to install it?
