### ISSUE TITLE
[REQUEST] restrict digraph completion to a subset

### ISSUE THREAD

**Issue by step-** [chrisbra/unicode.vim#8]
Hi, thanks for this vim plugin! I use digraph completion most often, and UnicodeName mapped to ga.

With the current implementation, all characters that combine to a digraph, any digraph, are converted in a visual selection. Instead, would it be possible to restrict completion to a user-defined digraph subset? In most practical cases, this would allow visually selecting all text in the file and pressing F4 to convert all non-converted digraphs -- and _those digraphs only_ -- in one fell swoop, instead of having to dig down the file for each unconverted digraph and change it with visual F4 one by one.

For instance, `g:digraph_output_subset` could be set to an array of decimal codes corresponding to the requested output digraphs, and the plugin would convert only character pairs that combined into one of those codes.

Thanks for your consideration.

P.S. I tried reproducing the `Digraphs! A` example found in unicode.txt help file, but nothing happens. It seems the plugin is stuck waiting for something or taking too long to complete (at least a minute). I can interrupt it and return to vim by pressing Ctrl+C. Other examples in unicode.txt seem to work.

**Comment by chrisbra** [comment]
Hi stepk!

On Mo, 31 Aug 2015, stepk wrote:

> Hi, thanks for this vim plugin! I use digraph completion most often, and UnicodeName mapped to ga.
> 
> With the current implementation, all characters that combine to a digraph, any digraph, are converted in a visual selection. Instead, would it be possible to restrict completion to a user-defined digraph subset? In most practical cases, this would allow visually selecting all text in the file and pressing F4 to convert all non-converted digraphs -- and _those digraphs only_ -- in one fell swoop, instead of having to dig down the file for each unconverted digraph and change it with visual F4 one by one.
> 
> For instance, `g:digraph_output_subset` could be set to an array of decimal codes corresponding to the requested output digraphs, and the plugin would convert only character pairs that combined into one of those codes.


Good suggestion. This is probably a little bit tricky, because one needs 
to check the resulting digraph. I'll see what I can do for you. 
> 
> Thanks for your consideration.
> 
> P.S. I tried reproducing the `Digraphs! A` example found in unicode.txt help file, but nothing happens. It seems the plugin is stuck waiting for something or taking too long to complete (at least a minute). I can interrupt it and return to vim by pressing Ctrl+C. Other examples in unicode.txt seem to work.

Thanks for the hint. There was indeed some old code lying around, that 
made it slow down considerably. I fixed that and push an  update soon.

Best,
Christian
-- 
Große Schatten werfen ihre Ereignisse hinter sich.
		-- Heinz Erhardt

**Comment by step-** [comment]
Thanks for this! I pulled then tested the following example (save the file and source it, then follow the comments). As you can see the converted output is out of place, and there are some spurious characters too.
```
" 1:a2 34:o56 base
" 1:a2 34:o56 selecte me and convert once
" converted output below
" " 1:a2 34ö56 selecte e me and äconvert t once

let g:Unicode_ConvertDigraphSubset = [ 
	\ char2nr("€"),
	\ char2nr("ä"),
	\ char2nr("Ä"),
	\ char2nr("ö"),
	\ char2nr("Ö"),
	\ char2nr("ü"),
	\ char2nr("Ü"),
	\ char2nr("ß") ]
```

**Comment by chrisbra** [comment]
Hi stepk!

On Di, 01 Sep 2015, stepk wrote:

> Thanks for this! I pulled then tested the following example (save the file and source it, then follow the comments). As you can see the converted output is out of place, and there are some spurious characters too.
> ```
> " 1:a2 34:o56 base
> " 1:a2 34:o56 selecte me and convert once
> " converted output below
> " " 1:a2 34ö56 selecte e me and äconvert t once
> 
> let g:Unicode_ConvertDigraphSubset = [ 
> 	\ char2nr("€"),
> 	\ char2nr("ä"),
> 	\ char2nr("Ä"),
> 	\ char2nr("ö"),
> 	\ char2nr("Ö"),
> 	\ char2nr("ü"),
> 	\ char2nr("Ü"),
> 	\ char2nr("ß") ]
> ```

I see one problem, that the :a is not converted to 'ä'. This is because 
the space is handled specifically. If you add a e.g. another letter 
before the 1 it works. 

This is a bug, that I just fixed. The actual problem remains however. 
characters will always be tried to converted in pairs of 2. If however 
the ':' is handled with the letter in front of it and the 'a' with the 
latter after it, it won't work. I need to think, if this can be avoided.

Other than that, I don't see the problem with the spurious characters.

Best,
Christian
-- 
Wenn Argumente fehlen, kommt meist ein Verbot heraus.
		-- Oliver Hassencamp

**Comment by step-** [comment]
I just pulled  54a011fc95e and tested it with the same file. No digraphs got converted. I got this output:
```
" 1:a2 34:o56 selecte me and convert once
e
```
This is output, not input. You can see that 'e' was appended after 'select' and also on a new line.
I generated this by visually selecting the second line in the above script and pressing F4.

**Comment by chrisbra** [comment]
Hi stepk!

On Di, 01 Sep 2015, stepk wrote:

> I just pulled  54a011fc95e and tested it with the same file. No digraphs got converted. I got this output:
> ```
> " 1:a2 34:o56 selecte me and convert once
> e
> ```
> This is output, not input. You can see that 'e' was appended after 'select' and also on a new line.
> I generated this by visually selecting the second line in the above script and pressing F4.

Thanks, I think I could reproduce the issue. I changed the way the 
digraphs are generated slightly and my tests pass. Could you please 
re-test?

Best,
Christian
-- 
Jeder Freund hält es für den größten Genuß, dem andern die Wahrheit zu
sagen - am Hören findet keiner einen sonderlichen.
		-- Jean Paul

**Comment by step-** [comment]
Getting closer. This is the converted output, same steps to generate it as before:
```
" 1ä2 34ö56 selecte me anäconvert once
```
The conversion went well, but a spurious "ä" replaced "d " where it shouldn't.
I'm going to test again without other vim plugins loaded. Will be back with more results later...

**Comment by chrisbra** [comment]
Hi stepk!

On Di, 01 Sep 2015, stepk wrote:

> Getting closer. This is the converted output, same steps to generate it as before:
> ```
> " 1ä2 34ö56 selecte me anäconvert once
> ```
> The conversion went well, but a spurious "ä" replaced "d " where it shouldn't.
> I'm going to test again without other vim plugins loaded. Will be back with more results later...

Ah see the problem. <Space> char will generate a digraph with the high 
bit set, e.g. 'a ' will be converted. This is mentioned in the help at 
:h digraph and then search for space

This is most likely unwanted as you can see. So let's make the plugin 
ignore a space, when one is encountered. I have pushed another updated.

Best,
Christian
-- 
Hier wird zwar nicht viel gemacht, aber was gemacht wird, ist nicht zu
gebrauchen.

**Comment by step-** [comment]
Hi Christian,

Great, it works as expected now! Thanks for squashing this issue.

I discovered a new corner case. Start with a blank file. Add just one line
```
a.
```
characters 'a' and '.'. Now v-select the line and press F4. I get message "error detected while processing function unicode#GetDigraph\nline 27:". The converted line looks incorrectly like this
```
a.0
```
If instead of starting this test with "a." I start it with "a.x" there is no error message and the converted line looks correctly like this
```
a.x
```
since "a." isn't a valid digraph the line is correctly left unchanged.

**Comment by chrisbra** [comment]
Hi stepk!

On Mi, 02 Sep 2015, stepk wrote:

> Hi Christian,
> 
> Great, it works as expected now! Thanks for squashing this issue.
> 
> I discovered a new corner case. Start with a blank file. Add just one line
> ```
> a.
> ```
> characters 'a' and '.'. Now v-select the line and press F4. I get message "error detected while processing function unicode#GetDigraph\nline 27:". The converted line looks incorrectly like this
> ```
> a.0
> ```
> If instead of starting this test with "a." I start it with "a.x" there is no error message and the converted line looks correctly like this
> ```
> a.x
> ```
> since "a." isn't a valid digraph the line is correctly left unchanged.

Good observation. I think i fixed that.

Best,
Christian
-- 
Wer viel lernt, weiß viel.
Wer viel weiß, vergißt viel.
Wer viel vergißt, weiß wenig.
Warum lernst Du eigentlich?

**Comment by step-** [comment]
It's fixed. Thank you very much, Christian!
