### ISSUE TITLE
Getting errors after update

### ISSUE THREAD

**Issue by daveyarwood** [chrisbra/unicode.vim#9]
Hi -- unicode.vim is great! I've really been enjoying it.

I did run into some errors just now after updating my Vundle plugins.

The first time I try to use `:UnicodeName` (which I have mapped to `ga`) after starting Vim, I get this error:

<img width="482" alt="vim-unicode-error" src="https://cloud.githubusercontent.com/assets/4909079/10668514/9d8d4260-78aa-11e5-8db8-c1317a7f9d3d.png">

After that, whenever I use `:UnicodeName`, it does what it's supposed to do, but I also get another error:

<img width="465" alt="screen shot 2015-10-22 at 10 49 14 am" src="https://cloud.githubusercontent.com/assets/4909079/10668515/9fc08038-78aa-11e5-8601-80b5a707f9c8.png">

**Comment by chrisbra** [comment]
Sorry for that. I think I have just fixed that error. Please test.

**Comment by daveyarwood** [comment]
That fixed it. Thanks so much!
